# Generated by Django 5.2.6 on 2025-09-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsData',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_tech', models.CharField(max_length=200)),
                ('project_desc', models.TextField()),
                ('project_img', models.ImageField(upload_to='images/')),
                ('project_github', models.URLField()),
                ('project_demo', models.URLField(blank=True)),
                ('project_features', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ProtofolioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_img', models.ImageField(upload_to='images/')),
                ('aboutme_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
